10 postgis import data of buildings needed to teach model
RadekBucki/ADoTO-Backend pull request #14
Opened 2023-04-04 21:22 UTC by JakubCzyzewski-TomTom

2023-04-04 21:52 UTC, RadekBucki requested changes

2023-04-04 21:52 UTC, RadekBucki commented on .env
> +POSTGRES_URL=jdbc:postgresql://host.docker.internal:${POSTGRES_LOCAL_PORT}/${POSTGRES_DATABASE}
I think that probably this cause fail of github workflow

2023-04-04 21:52 UTC, RadekBucki commented on src/main/java/pl/ioad/adoto/database/DBService.java
> +@org.springframework.stereotype.Service
Please add this to import

2023-04-04 21:52 UTC, RadekBucki commented on src/main/java/pl/ioad/adoto/database/dto/BuildingDTO.java
> +    GeometryDTO geometry;
Missed access qualifiers

2023-04-04 21:52 UTC, RadekBucki commented on src/main/java/pl/ioad/adoto/database/dto/GeometryDTO.java
> +    String type;
Missed access qualifiers

2023-04-05 08:54 UTC, RadekBucki approved these changes

2023-04-07 15:50 UTC, Damian2057 approved these changes

2023-04-08 10:09 UTC, merged