svg converter implementation
RadekBucki/ADoTO-Backend pull request #24
Opened 2023-04-18 17:42 UTC by filipgrzelak

2023-04-18 17:56 UTC, RadekBucki requested changes

2023-04-18 17:56 UTC, RadekBucki commented on src/main/java/pl/ioad/adoto/backend/svg/converter/SvgConverter.java
> +            coordinates.add(new BigDecimal(d.get(i)));
Could me simplified with
```suggestion
            String result = d.get(i);
            if (i % 2 == 0) {
                result = result.substring(1, result.length() - 1);
            }
            coordinates.add(new BigDecimal(result));
```

2023-04-19 18:35 UTC, RadekBucki approved these changes

2023-04-19 18:51 UTC, Damian2057 approved these changes

2023-04-19 18:51 UTC, merged